/// <reference types="Cypress" />

it("Rplenishment of Ukraine mobile phone number", () => {
  cy.visit("https://next.privat24.ua/mobile?lang=en")
    .get('[data-qa-node="phone-number"]')
    .type(939393933)
    .get('[data-qa-node="amount"]')
    .clear()
    .type(100)
    .get('[data-qa-node="numberdebitSource"]')
    .type(4552331448138217)
    .get('[data-qa-node="expiredebitSource"]')
    .type("05 / 24")
    .get('[data-qa-node="cvvdebitSource"]')
    .type(111)
    .get('[data-qa-node="submit"]')
    .click()
    .wait(2000)
    .get('[data-qa-node="card"]')
    .should("have.text", "4552 **** **** 8217")
    .get('[data-qa-node="amount"]')
    .should("contain.text", "100")
    .and("contain.text", "UAH")
    .get('[data-qa-node="commission"]')
    .should("contain.text", "2")
    .get('[data-qa-node="commission-currency"]')
    .should("contain.text", "UAH");
});

it.only("Money transfer between foreign cards", () => {
  cy.visit("https://next.privat24.ua/money-transfer/card?lang=en")
    .get('[data-qa-node="numberdebitSource"]')
    .type(4552331448138217)
    .get('[data-qa-node="expiredebitSource"]')
    .type("05 / 24")
    .get('[data-qa-node="cvvdebitSource"]')
    .type(111)
    .get('[data-qa-node="firstNamedebitSource"]')
    .type("Shayne")
    .get('[data-qa-node="lastNamedebitSource"]')
    .type("McConnell")
    .get('[data-qa-node="numberreceiver"]')
    .type(5309233034765085)
    .get('[data-qa-node="firstNamereceiver"]')
    .type("Juliana")
    .get('[data-qa-node="lastNamereceiver"]')
    .type("Janssen")
    .get('[data-qa-node="amount"]')
    .type(100)
    .get('[data-qa-node="currency"]')
    .click()
    .get('[data-qa-value="USD"]')
    .click()
    .get('[data-qa-node="toggle-comment"]')
    .click()
    .get('[data-qa-node="comment"]')
    .type("TransFer")
    .get('[type="submit"]')
    .click()
    .wait(2000)
    .get('[data-qa-node="payer-card"]')
    .should("have.text", "4552 3314 4813 8217")
    .get('[data-qa-node="receiver-card"]')
    .should("have.text", "5309 2330 3476 5085")
    .get('[data-qa-node="payer-amount"]')
    .should("have.text", "100 USD")
    .get('[data-qa-node="receiver-amount"]')
    .should("have.text", "100 USD")
    .get('[data-qa-node="payer-currency"]')
    .should("have.text", "4.95 USD")
    .get('[data-qa-node="receiver-currency"]')
    .should("have.text", "0 USD")
    .get('[data-qa-node="total"]')
    .should("contain.text", "104.95")
    .and("contain.text", "USD")
    .get('[data-qa-node="comment"]')
    .should("contain.text", "TransFer");
});
